import { createSupabaseServerClient } from "../../lib/supabase/server";

export const dynamic="force-dynamic";
function dateKey(v){return new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Accra",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(v));}
function fmt(v){return v?new Intl.DateTimeFormat("en-GH",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Africa/Accra"}).format(new Date(v)):"Date TBC";}
function Team({team}){return <div className="mc-team"><div className="mc-logo">{team?.logo_url?<img src={team.logo_url} alt=""/>:<span>{(team?.short_name||team?.name||"?").slice(0,2).toUpperCase()}</span>}</div><strong>{team?.short_name||team?.name||"Team TBC"}</strong></div>;}

export default async function MatchesPage(){
 const s=createSupabaseServerClient();
 const [{data:matches,error:me},{data:verifications,error:ve}]=await Promise.all([
  s.from("matches").select("id,scheduled_at,status,home_score,away_score,home_team:teams!matches_home_team_id_fkey(id,name,short_name,logo_url),away_team:teams!matches_away_team_id_fkey(id,name,short_name,logo_url),season:seasons(id,name,competition:competitions(id,name))").order("scheduled_at",{ascending:true}).limit(200),
  s.from("match_verifications").select("match_id").eq("official_result",true)
 ]);
 const error=me||ve,official=new Set((verifications||[]).map(x=>x.match_id)),today=dateKey(new Date());
 const visible=(matches||[]).filter(m=>dateKey(m.scheduled_at)===today||["live","in_progress","halftime","paused"].includes(m.status)).filter(m=>{const live=["live","in_progress","halftime","paused"].includes(m.status),finished=["finished","verified"].includes(m.status);return live||(!finished&&new Date(m.scheduled_at)>=new Date())||(official.has(m.id)&&finished);});
 return <main><section className="container page-hero"><span className="section-kicker">Zedek Sports</span><h1>Match Centre</h1><p>Fixtures, live football and verified results from local football across Oti.</p></section><section className="container match-centre"><div className="mc-date-strip"><div className="mc-day active"><b>Today</b><span>{new Intl.DateTimeFormat("en-GH",{day:"numeric",month:"short",timeZone:"Africa/Accra"}).format(new Date())}</span></div><label className="mc-calendar"><span>Calendar</span><input type="date" defaultValue={today}/></label></div><div className="mc-tabs"><span className="mc-tab active">All football</span><span className="mc-tab">Upcoming</span><span className="mc-tab">Live</span><span className="mc-tab">Results</span></div>{error?<div className="data-note">{error.message}</div>:!visible.length?<div className="empty-state"><strong>No published matches for today.</strong><span>Official fixtures and verified results will appear automatically.</span></div>:<div className="match-list">{visible.map(m=>{const live=["live","in_progress","halftime","paused"].includes(m.status),off=official.has(m.id);return <a className="mc-match" href={"/matches/"+m.id} key={m.id}><div className="mc-meta"><span>{m.season?.competition?.name||"Competition TBC"}</span><span className={live?"live-dot":""}>{live?"LIVE":off?"OFFICIAL":fmt(m.scheduled_at)}</span></div><div className="mc-teams"><Team team={m.home_team}/><div className="mc-score">{live||off?<><b>{m.home_score??0}</b><span>—</span><b>{m.away_score??0}</b></>:<span>vs</span>}</div><Team team={m.away_team}/></div><div className="mc-footer"><span>{fmt(m.scheduled_at)}</span><span>View match →</span></div></a>})}</div>}</section></main>;
}