"use client";
import {useEffect,useState} from "react";
import {createSupabaseBrowserClient} from "../../lib/supabase/browser";
const sb=()=>typeof window==="undefined"?null:createSupabaseBrowserClient();
const fmt=v=>v?new Date(v).toLocaleString():"—";
export default function ReportersAdminPage(){
 const [loading,setLoading]=useState(true),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[reporters,setReporters]=useState([]),[matches,setMatches]=useState([]),[assignments,setAssignments]=useState([]),[form,setForm]=useState({reporter_id:"",match_id:"",notes:""}),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function refresh(){const s=sb();const [r,m,a]=await Promise.all([s.from("profiles").select("id,full_name,phone,is_active").eq("role","reporter").eq("is_active",true).order("full_name"),s.from("matches").select("*,home:teams!matches_home_team_id_fkey(name),away:teams!matches_away_team_id_fkey(name),seasons(name),stages(name)").order("scheduled_at",{ascending:true}),s.from("reporter_assignments").select("*").order("created_at",{ascending:false})]);const bad=[r,m,a].find(x=>x.error);if(bad){setError(bad.error.message);return;}setReporters(r.data||[]);setMatches(m.data||[]);setAssignments(a.data||[]);}
 useEffect(()=>{let mounted=true;async function boot(){const s=sb(),me=await s.auth.getUser();if(me.error||!me.data.user){location.href="/login";return;}setUser(me.data.user);const p=await s.from("profiles").select("id,full_name,role,is_active").eq("id",me.data.user.id).maybeSingle();if(!mounted)return;if(p.error){setError(p.error.message);setLoading(false);return;}setProfile(p.data);if(p.data?.is_active&&["super_admin","zedek_admin"].includes(p.data.role))await refresh();setLoading(false);}boot();return()=>{mounted=false};},[]);
 async function assign(e){e.preventDefault();if(!form.reporter_id||!form.match_id){setError("Select a reporter and match.");return;}setSaving(true);setError("");const duplicate=assignments.find(a=>a.reporter_id===form.reporter_id&&a.match_id===form.match_id&&a.status!=="cancelled");if(duplicate){setError("That reporter is already assigned to this match.");setSaving(false);return;}const r=await sb().from("reporter_assignments").insert({reporter_id:form.reporter_id,match_id:form.match_id,status:"assigned",notes:form.notes.trim()||null}).select("*").single();setSaving(false);if(r.error){setError(r.error.message);return;}setNotice("Reporter assigned successfully.");setForm({reporter_id:"",match_id:"",notes:""});await refresh();}
 async function setStatus(a,status){setSaving(true);const v={status};if(status==="completed")v.completed_at=new Date().toISOString();if(status==="cancelled")v.completed_at=null;const r=await sb().from("reporter_assignments").update(v).eq("id",a.id);setSaving(false);if(r.error)setError(r.error.message);else{setNotice("Assignment updated.");await refresh();}}
 async function signOut(){await sb().auth.signOut();location.href="/login";}
 const active=assignments.filter(a=>a.status!=="cancelled");
 if(loading)return <main className="auth-page"><div className="panel">Loading Reporter Management…</div></main>;
 if(!user||!profile||!profile.is_active||![\"super_admin\",\"zedek_admin\"].includes(profile.role))return <main className="auth-page"><div className="panel"><h1>Access restricted</h1><p>{error||"Administrator access is required."}</p><button className="button" onClick={signOut}>Sign out</button></div></main>;
 return <main className="page"><header className="site-header"><div className="container nav"><div className="brand">ZEDEK <span>SPORTS</span> · CONTROL</div><div style={{display:"flex",gap:8}}><a className="button" href="/">Control Room</a><button className="button" onClick={signOut}>Sign out</button></div></div></header><section className="container page-header"><div className="eyebrow">Phase 2 · Football Operations</div><h1>Reporter Management</h1><p>Assign restricted reporter accounts to specific matches. Reporters never receive administrator controls.</p></section><section className="container">{error&&<div className="error-box">{error}</div>}{notice&&<div className="success-box">{notice}</div>}
 <div className="stats-grid"><form className="panel form-stack" onSubmit={assign}><h2>Assign reporter</h2><label>Reporter<select required value={form.reporter_id} onChange={e=>setForm({...form,reporter_id:e.target.value})}><option value="">Select reporter</option>{reporters.map(r=><option key={r.id} value={r.id}>{r.full_name||"Unnamed reporter"}{r.phone?" · "+r.phone:""}</option>)}</select></label><label>Match<select required value={form.match_id} onChange={e=>setForm({...form,match_id:e.target.value})}><option value="">Select match</option>{matches.filter(m=>!["finished","verified","cancelled"].includes(m.status)).map(m=><option key={m.id} value={m.id}>{m.home?.name} vs {m.away?.name} · {m.scheduled_at?fmt(m.scheduled_at):"Kickoff TBC"}</option>)}</select></label><label>Assignment note<textarea rows="4" placeholder="Optional instructions for the reporter" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="button primary" disabled={saving}>{saving?"Assigning…":"Assign reporter"}</button><p className="muted">RLS restricts reporters to their own assignments and assigned matches.</p></form><div className="panel"><h2>Reporter accounts</h2>{reporters.map(r=><div className="status-card" key={r.id}><b>{r.full_name||"Unnamed reporter"}</b><span>{r.phone||"No phone"} · ACTIVE</span><span>Active assignments: {active.filter(a=>a.reporter_id===r.id).length}</span></div>)}{!reporters.length&&<p className="muted">No active reporter accounts. Create/authenticate a user and set its profile role to reporter.</p>}</div></div>
 <div className="panel" style={{marginTop:16}}><h2>Assignment queue</h2>{active.map(a=>{const r=reporters.find(x=>x.id===a.reporter_id),m=matches.find(x=>x.id===a.match_id);return <div className="status-card" key={a.id}><b>{m?.home?.name||"Home"} vs {m?.away?.name||"Away"}</b><span>{r?.full_name||"Reporter"} · {m?.scheduled_at?fmt(m.scheduled_at):"Kickoff TBC"} · {m?.status||"scheduled"}</span><span>Assignment: {a.status}{a.notes?" · "+a.notes:""}</span><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}>{!["completed","cancelled"].includes(a.status)&&<button className="button primary" disabled={saving} onClick={()=>setStatus(a,"completed")}>Mark completed</button>}{!["completed","cancelled"].includes(a.status)&&<button className="button" disabled={saving} onClick={()=>setStatus(a,"cancelled")}>Cancel assignment</button>}</div></div>})}{!active.length&&<p className="muted">No active reporter assignments.</p>}</div></section></main>;
}
