"use client";

import { useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "../../../lib/supabase/browser";

type Match={id:string;home_team_id:string;away_team_id:string;scheduled_at:string|null;venue:string|null;status:string;home_score:number;away_score:number;round_name:string|null;notes:string|null};
type Team={id:string;name:string};
type Event={id:string;match_id:string;team_id:string|null;player_id:string|null;event_type:string;minute:number|null;extra_minute:number|null;details:string|null};
type Player={id:string;team_id:string;full_name:string;shirt_number:number|null};
type Stats=Record<string,number|string>;
const statFields=[
 ["home_possession","Possession %"],["away_possession","Possession %"],["home_shots","Shots"],["away_shots","Shots"],
 ["home_shots_on_target","Shots on target"],["away_shots_on_target","Shots on target"],["home_corners","Corners"],["away_corners","Corners"],
 ["home_fouls","Fouls"],["away_fouls","Fouls"],["home_offsides","Offsides"],["away_offsides","Offsides"],
 ["home_saves","Saves"],["away_saves","Saves"],["home_passes","Passes"],["away_passes","Passes"],
 ["home_pass_accuracy","Pass accuracy %"],["away_pass_accuracy","Pass accuracy %"],["home_crosses","Crosses"],["away_crosses","Crosses"],
 ["home_free_kicks","Free kicks"],["away_free_kicks","Free kicks"],["home_goal_kicks","Goal kicks"],["away_goal_kicks","Goal kicks"],
 ["home_throw_ins","Throw-ins"],["away_throw_ins","Throw-ins"],["home_xg","xG"],["away_xg","xG"]
] as const;

export default function MatchControlPage(){
 const [matches,setMatches]=useState<Match[]>([]),[teams,setTeams]=useState<Team[]>([]),[players,setPlayers]=useState<Player[]>([]),[events,setEvents]=useState<Event[]>([]);
 const [selected,setSelected]=useState(""),[stats,setStats]=useState<Stats>({}),[eventType,setEventType]=useState("goal"),[eventTeam,setEventTeam]=useState(""),[eventPlayer,setEventPlayer]=useState(""),[minute,setMinute]=useState(""),[extra,setExtra]=useState(""),[details,setDetails]=useState("");
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[now,setNow]=useState(Date.now());
 const match=matches.find(m=>m.id===selected); const home=teams.find(t=>t.id===match?.home_team_id),away=teams.find(t=>t.id===match?.away_team_id);
 const roster=useMemo(()=>players.filter(p=>p.team_id===eventTeam),[players,eventTeam]);
 useEffect(()=>{load()},[]);
 useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(x)},[]);
 async function load(){setLoading(true);const s=createSupabaseBrowserClient();const [m,t,p]=await Promise.all([s.from("matches").select("id,home_team_id,away_team_id,scheduled_at,venue,status,home_score,away_score,round_name,notes").in("status",["scheduled","live","halftime","suspended","postponed"]).order("scheduled_at",{ascending:true,nullsFirst:false}),s.from("teams").select("id,name").order("name"),s.from("players").select("id,team_id,full_name,shirt_number").eq("is_active",true).order("full_name")]);if(m.error||t.error||p.error)setError(m.error?.message||t.error?.message||p.error?.message||"Could not load match control.");else{setMatches(m.data||[]);setTeams(t.data||[]);setPlayers(p.data||[]);if(!selected&&m.data?.length)setSelected(m.data[0].id)}setLoading(false)}
 async function selectMatch(id:string){setSelected(id);setError("");const s=createSupabaseBrowserClient();const [e,st]=await Promise.all([s.from("match_events").select("*").eq("match_id",id).order("created_at",{ascending:true}),s.from("match_statistics").select("*").eq("match_id",id).maybeSingle()]);if(e.error||st.error)setError(e.error?.message||st.error?.message||"Could not load match data.");else{setEvents(e.data||[]);setStats(st.data||{})}}
 useEffect(()=>{if(selected)selectMatch(selected)},[selected]);
 async function updateMatch(patch:Partial<Match>){
  if(!match)return;
  setBusy(true);setError("");setNotice("");
  const next=patch.status;
  if(next==="finished"&&!["live","halftime"].includes(match.status)){setError("A match can only be finished from live or half-time.");setBusy(false);return}
  if(next==="halftime"&&match.status!=="live"){setError("Half-time is only available during a live match.");setBusy(false);return}
  if(next==="live"&&!["scheduled","halftime"].includes(match.status)){setError("Kickoff/resume is only available from scheduled or half-time.");setBusy(false);return}
  const s=createSupabaseBrowserClient();
  const {error}=await s.from("matches").update(patch).eq("id",match.id);
  if(error)setError(error.message);else{setNotice("Match updated.");await load()}
  setBusy(false)
}
 function elapsed(){if(!match?.scheduled_at||match.status!=="live")return 0;return Math.max(0,Math.floor((now-new Date(match.scheduled_at).getTime())/60000))}
 async function addEvent(){
  if(!match||!eventTeam||!eventType)return;
  if(!["live","halftime"].includes(match.status)){setError("Match events can only be recorded while live or at half-time.");return}
  const m=minute?Number(minute):elapsed();
  if(!Number.isInteger(m)||m<0||m>120){setError("Minute must be between 0 and 120.");return}
  const x=extra?Number(extra):null;
  if(x!==null&&(!Number.isInteger(x)||x<0||x>30)){setError("Added time must be between 0 and 30.");return}
  setBusy(true);setError("");setNotice("");const s=createSupabaseBrowserClient();const {error}=await s.from("match_events").insert({match_id:match.id,team_id:eventTeam,player_id:eventPlayer||null,event_type:eventType,minute:m,extra_minute:x,details:details.trim()||null});if(error)setError(error.message);else{if(eventType==="goal"||eventType==="own_goal"){const isHome=eventTeam===match.home_team_id;const field=eventType==="goal"?(isHome?"home_score":"away_score"):(isHome?"away_score":"home_score");const score=field==="home_score"?match.home_score:match.away_score;const scoreUpdate=await s.from("matches").update({[field]:score+1}).eq("id",match.id);if(scoreUpdate.error){await s.from("match_events").delete().eq("id",e.id);setError("Goal recorded, but score update failed; event was rolled back.");await selectMatch(match.id);await load();setBusy(false);return}}setEventPlayer("");setMinute("");setExtra("");setDetails("");await selectMatch(match.id);await load()}setBusy(false)}
 async function saveStats(){if(!match)return;const values=Object.fromEntries(statFields.map(([k])=>[k,Number(stats[k]??0)]));for(const [key,value] of Object.entries(values)){if(!Number.isFinite(value)||value<0){setError("Statistics must be non-negative numbers.");return}if((key.includes("possession")||key.includes("pass_accuracy"))&&value>100){setError("Percent statistics must be between 0 and 100.");return}if(!key.includes("xg")&&!key.includes("possession")&&!key.includes("pass_accuracy")&&!Number.isInteger(value)){setError("Count statistics must be whole numbers.");return}}const possession=Number(values.home_possession)+Number(values.away_possession);if(possession>100.001){setError("Home and away possession cannot total more than 100%.");return}setBusy(true);setError("");const s=createSupabaseBrowserClient();const payload={match_id:match.id,...values,updated_at:new Date().toISOString()};const {error}=await s.from("match_statistics").upsert(payload);if(error)setError(error.message);else setNotice("Live match statistics saved.");setBusy(false)}
 return <main className="page"><header className="site-header"><div className="container nav"><a className="brand" href="/control-room">ZEDEK <span>SPORTS</span></a><nav className="nav-links"><a href="/control-room/fixtures">Fixtures</a><a href="/control-room">Dashboard</a></nav></div></header>
 <section className="container page-header"><div className="eyebrow">Football Operations · Match Control</div><h1>Live Match Control</h1><p>Operate the match from kickoff through half-time and full-time, while recording events and live statistics.</p></section>
 <section className="container section"><div className="panel"><label>Select match<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a match</option>{matches.map(m=><option key={m.id} value={m.id}>{teams.find(t=>t.id===m.home_team_id)?.name||"Home"} vs {teams.find(t=>t.id===m.away_team_id)?.name||"Away"} · {m.status}</option>)}</select></label></div></section>
 {match&&<><section className="container section"><div className="panel match-control"><div className="section-heading"><div><h2>{home?.name} vs {away?.name}</h2><small>{match.venue||"Venue not set"} · {match.round_name||"No round"}</small></div><strong>{match.home_score} - {match.away_score}</strong></div><div className="status-card"><b>{match.status.toUpperCase()}</b>{match.status==="live"&&<span> Match minute: {elapsed()}'</span>}</div><div className="button-row">{match.status==="scheduled"&&<button className="button primary" disabled={busy} onClick={()=>updateMatch({status:"live",scheduled_at:new Date().toISOString()})}>Kick Off</button>}{match.status==="live"&&<button className="button" disabled={busy} onClick={()=>updateMatch({status:"halftime"})}>Half-time</button>}{match.status==="halftime"&&<button className="button primary" disabled={busy} onClick={()=>updateMatch({status:"live",scheduled_at:new Date(Date.now()-45*60000).toISOString()})}>Resume 2nd Half</button>}{["live","halftime"].includes(match.status)&&<button className="button primary" disabled={busy} onClick={()=>updateMatch({status:"finished"})}>Finish Match</button>}{match.status!=="finished"&&<button className="button danger" disabled={busy} onClick={()=>updateMatch({status:"suspended"})}>Suspend</button>}</div></div></section>
 <section className="container section"><div className="panel"><h2>Match event</h2><div className="form-stack"><label>Event type<select value={eventType} onChange={e=>setEventType(e.target.value)}><option>goal</option><option>own_goal</option><option>yellow_card</option><option>red_card</option><option>substitution</option><option>injury</option><option>note</option></select></label><label>Team<select value={eventTeam} onChange={e=>{setEventTeam(e.target.value);setEventPlayer("")}}><option value="">Select team</option><option value={match.home_team_id}>{home?.name}</option><option value={match.away_team_id}>{away?.name}</option></select></label><label>Player<select value={eventPlayer} onChange={e=>setEventPlayer(e.target.value)}><option value="">Optional player</option>{roster.map(p=><option key={p.id} value={p.id}>{p.shirt_number?("#"+p.shirt_number+" "):""}{p.full_name}</option>)}</select></label><label>Minute<input type="number" min="0" value={minute} onChange={e=>setMinute(e.target.value)} placeholder={String(elapsed())}/></label><label>Added time<input type="number" min="0" value={extra} onChange={e=>setExtra(e.target.value)}/></label><label>Details<input value={details} onChange={e=>setDetails(e.target.value)}/></label><button className="button primary" disabled={busy||!eventTeam} onClick={addEvent}>Record event</button></div><div className="module-grid">{events.map(e=><article className="module" key={e.id}><strong>{e.minute??"-"}' {e.event_type}</strong><small>{e.team_id?teams.find(t=>t.id===e.team_id)?.name:""} {e.player_id?"· "+(players.find(p=>p.id===e.player_id)?.full_name||""):""}</small><small>{e.details||""}</small></article>)}</div></div></section>
 <section className="container section"><div className="panel"><div className="section-heading"><h2>Live statistics</h2><button className="button primary" disabled={busy} onClick={saveStats}>Save statistics</button></div><div className="module-grid">{statFields.map(([key,label])=><label key={key}>{label} <small>{key.startsWith("home_")?home?.name:away?.name}</small><input type="number" step={key.includes("xg")?0.001:0.01} value={stats[key]??0} onChange={e=>setStats({...stats,[key]:e.target.value})}/></label>)}</div></div></section></>}
 {loading&&<p className="container">Loading match control...</p>}{notice&&<div className="container success-box">{notice}</div>}{error&&<div className="container error-box">{error}</div>}</main>
}