"use client";
import { useEffect,useMemo,useState } from "react";
import { createSupabaseBrowserClient } from "../../../lib/supabase/browser";

type Match={id:string;home_team_id:string;away_team_id:string;scheduled_at:string|null;status:string};
type Team={id:string;name:string};
type Player={id:string;team_id:string;full_name:string;shirt_number:number|null;position:string|null};
type Coach={id:string;full_name:string;role:string};
type Lineup={id:string;match_id:string;team_id:string;coach_id:string|null;formation:string|null;captain_player_id:string|null;submitted_at:string|null};
type LP={id:string;lineup_id:string;player_id:string;role:string;shirt_number:number|null;position:string|null};

export default function LineupsPage(){
 const [matches,setMatches]=useState<Match[]>([]),[teams,setTeams]=useState<Team[]>([]),[players,setPlayers]=useState<Player[]>([]),[coaches,setCoaches]=useState<Coach[]>([]),[lineups,setLineups]=useState<Lineup[]>([]),[lineupPlayers,setLineupPlayers]=useState<LP[]>([]);
 const [matchId,setMatchId]=useState(""),[teamId,setTeamId]=useState(""),[coachId,setCoachId]=useState(""),[formation,setFormation]=useState("4-3-3"),[captain,setCaptain]=useState(""),[starters,setStarters]=useState<string[]>([]),[subs,setSubs]=useState<string[]>([]);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const match=matches.find(m=>m.id===matchId); const teamPlayers=useMemo(()=>players.filter(p=>p.team_id===teamId),[players,teamId]); const teamLineup=lineups.find(l=>l.match_id===matchId&&l.team_id===teamId);
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(teamLineup){setCoachId(teamLineup.coach_id||"");setFormation(teamLineup.formation||"4-3-3");setCaptain(teamLineup.captain_player_id||"");const ids=lineupPlayers.filter(x=>x.lineup_id===teamLineup.id);setStarters(ids.filter(x=>x.role==="starter").map(x=>x.player_id));setSubs(ids.filter(x=>x.role==="substitute").map(x=>x.player_id))}else{setCoachId("");setCaptain("");setStarters([]);setSubs([])}},[teamLineup,lineupPlayers]);
 async function load(){setLoading(true);const s=createSupabaseBrowserClient();const [m,t,p,c,l,lp]=await Promise.all([s.from("matches").select("id,home_team_id,away_team_id,scheduled_at,status").in("status",["scheduled","postponed","suspended"]).order("scheduled_at",{ascending:true,nullsFirst:false}),s.from("teams").select("id,name").order("name"),s.from("players").select("id,team_id,full_name,shirt_number,position").eq("is_active",true).order("full_name"),s.from("coaches").select("id,full_name,role").eq("is_active",true).order("full_name"),s.from("match_lineups").select("*"),s.from("match_lineup_players").select("*")]);const err=m.error||t.error||p.error||c.error||l.error||lp.error;if(err)setError(err.message);else{setMatches(m.data||[]);setTeams(t.data||[]);setPlayers(p.data||[]);setCoaches(c.data||[]);setLineups(l.data||[]);setLineupPlayers(lp.data||[]);if(!matchId&&m.data?.length)setMatchId(m.data[0].id)}setLoading(false)}
 function toggle(list:string[],id:string,setter:(v:string[])=>void){setter(list.includes(id)?list.filter(x=>x!==id):[...list,id])}
 async function save(){if(!match||!teamId)return;if(starters.length!==11){setError("A starting XI must contain exactly 11 players.");return}if(starters.includes(captain)===false){setError("Captain must be selected from the starting XI.");return}if(new Set([...starters,...subs]).size!==starters.length+subs.length){setError("A player cannot be both starter and substitute.");return}if(starters.length+subs.length>18){setError("Matchday squad cannot exceed 18 players.");return}setBusy(true);setError("");const s=createSupabaseBrowserClient();let lineupId=teamLineup?.id;if(lineupId){const {error}=await s.from("match_lineups").update({coach_id:coachId||null,formation,captain_player_id:captain,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",lineupId);if(error){setError(error.message);setBusy(false);return}await s.from("match_lineup_players").delete().eq("lineup_id",lineupId)}else{const {data,error}=await s.from("match_lineups").insert({match_id:match.id,team_id:teamId,coach_id:coachId||null,formation,captain_player_id:captain,submitted_at:new Date().toISOString()}).select("id").single();if(error||!data){setError(error?.message||"Could not create lineup.");setBusy(false);return}lineupId=data.id}const rows=[...starters.map(id=>({lineup_id:lineupId!,player_id:id,role:"starter",shirt_number:players.find(p=>p.id===id)?.shirt_number||null,position:players.find(p=>p.id===id)?.position||null})),...subs.map(id=>({lineup_id:lineupId!,player_id:id,role:"substitute",shirt_number:players.find(p=>p.id===id)?.shirt_number||null,position:players.find(p=>p.id===id)?.position||null}))];const {error}=await s.from("match_lineup_players").insert(rows);if(error)setError(error.message);else{setNotice("Lineup submitted successfully.");await load()}setBusy(false)}
 const teamName=teams.find(t=>t.id===teamId)?.name||"";
 return <main className="page"><header className="site-header"><div className="container nav"><a className="brand" href="/control-room">ZEDEK <span>SPORTS</span></a><nav className="nav-links"><a href="/control-room/fixtures">Fixtures</a><a href="/control-room/match-control">Match Control</a></nav></div></header>
 <section className="container page-header"><div className="eyebrow">Football Operations · Lineups</div><h1>Matchday Lineups</h1><p>Submit the starting XI, substitutes, captain, formation and coach before kickoff.</p></section>
 <section className="container section"><div className="panel"><div className="form-stack"><label>Match<select value={matchId} onChange={e=>{setMatchId(e.target.value);setTeamId("")}}><option value="">Select match</option>{matches.map(m=><option key={m.id} value={m.id}>{teams.find(t=>t.id===m.home_team_id)?.name} vs {teams.find(t=>t.id===m.away_team_id)?.name}</option>)}</select></label>{match&&<label>Team<select value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">Select team</option><option value={match.home_team_id}>{teams.find(t=>t.id===match.home_team_id)?.name}</option><option value={match.away_team_id}>{teams.find(t=>t.id===match.away_team_id)?.name}</option></select></label>}</div></div></section>
 {teamId&&<section className="container section"><div className="panel"><h2>{teamName}</h2><div className="form-stack"><label>Coach / Manager<select value={coachId} onChange={e=>setCoachId(e.target.value)}><option value="">Select coach</option>{coaches.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.role}</option>)}</select></label><label>Formation<select value={formation} onChange={e=>setFormation(e.target.value)}>{["4-3-3","4-4-2","4-2-3-1","3-5-2","3-4-3","5-3-2","4-5-1"].map(x=><option key={x}>{x}</option>)}</select></label><label>Captain<select value={captain} onChange={e=>setCaptain(e.target.value)}><option value="">Select captain</option>{teamPlayers.filter(p=>starters.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label></div><h3>Starting XI ({starters.length}/11)</h3><div className="module-grid">{teamPlayers.map(p=><button type="button" className={"button "+(starters.includes(p.id)?"primary":"")} key={p.id} onClick={()=>toggle(starters,p.id,setStarters)}>{p.shirt_number?("#"+p.shirt_number+" "):""}{p.full_name}<small>{p.position||"Position not set"}</small></button>)}</div><h3>Substitutes ({subs.length})</h3><div className="module-grid">{teamPlayers.filter(p=>!starters.includes(p.id)).map(p=><button type="button" className={"button "+(subs.includes(p.id)?"primary":"")} key={p.id} onClick={()=>toggle(subs,p.id,setSubs)}>{p.shirt_number?("#"+p.shirt_number+" "):""}{p.full_name}<small>{p.position||"Position not set"}</small></button>)}</div><button className="button primary" disabled={busy||starters.length!==11||!captain}>{busy?"Submitting...":teamLineup?"Update lineup":"Submit lineup"}</button></div></section>}
 {loading&&<p className="container">Loading...</p>}{notice&&<div className="container success-box">{notice}</div>}{error&&<div className="container error-box">{error}</div>}</main>
}