"use client";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "../../lib/supabase/browser";
const sb=()=>typeof window==="undefined"?null:createSupabaseBrowserClient();
const fmt=v=>v?new Date(v).toLocaleString():"—";
const elapsed=m=>{if(!m?.kickoff_at)return 0;const k=new Date(m.kickoff_at).getTime(),h=m.halftime_at?new Date(m.halftime_at).getTime():0,s=m.second_half_at?new Date(m.second_half_at).getTime():0,e=m.finished_at?new Date(m.finished_at).getTime():Date.now();return Math.max(0,Math.floor(((s?((h||s)-k)+(Math.min(e,Date.now())-s):(m.status==="halftime"?h:Math.min(e,Date.now()))-k))/1000));};
const clock=n=>String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0");
const statRows=[["home_possession","away_possession","Possession %",.1],["home_shots","away_shots","Shots",1],["home_shots_on_target","away_shots_on_target","Shots on target",1],["home_corners","away_corners","Corners",1],["home_fouls","away_fouls","Fouls",1],["home_offsides","away_offsides","Offsides",1],["home_saves","away_saves","Saves",1],["home_passes","away_passes","Passes",1],["home_pass_accuracy","away_pass_accuracy","Pass accuracy %",.1],["home_crosses","away_crosses","Crosses",1],["home_free_kicks","away_free_kicks","Free kicks",1],["home_goal_kicks","away_goal_kicks","Goal kicks",1],["home_throw_ins","away_throw_ins","Throw-ins",1],["home_xg","away_xg","Expected goals (xG)",.1]];
export default function ReporterPage(){
 const [loading,setLoading]=useState(true),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[assignments,setAssignments]=useState([]),[matches,setMatches]=useState([]),[players,setPlayers]=useState([]),[selectedId,setSelectedId]=useState(""),[events,setEvents]=useState([]),[stats,setStats]=useState(null),[report,setReport]=useState(null),[tick,setTick]=useState(0),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const selected=matches.find(x=>x.id===selectedId),assignment=assignments.find(x=>x.match_id===selectedId),[event,setEvent]=useState({type:"goal",team_id:"",player_id:"",secondary_player_id:"",minute:"",extra_minute:"",details:""});
 const eventPlayers=useMemo(()=>players.filter(p=>p.team_id===event.team_id),[players,event.team_id]);
 async function refresh(){const s=sb();const me=await s.auth.getUser();if(me.error||!me.data.user){location.href="/login";return;}setUser(me.data.user);const p=await s.from("profiles").select("id,full_name,role,is_active").eq("id",me.data.user.id).maybeSingle();if(p.error){setError(p.error.message);return;}setProfile(p.data);if(p.data?.role!=="reporter"||!p.data.is_active)return;const a=await s.from("reporter_assignments").select("*").eq("reporter_id",me.data.user.id).order("created_at",{ascending:false});if(a.error){setError(a.error.message);return;}const ids=(a.data||[]).map(x=>x.match_id);const [m,pl]=await Promise.all([ids.length?s.from("matches").select("*,home:teams!matches_home_team_id_fkey(name),away:teams!matches_away_team_id_fkey(name),seasons(name),stages(name)").in("id",ids):{data:[],error:null},s.from("players").select("id,team_id,full_name,shirt_number,position")]);const bad=[m,pl].find(x=>x.error);if(bad){setError(bad.error.message);return;}setAssignments(a.data||[]);setMatches(m.data||[]);setPlayers(pl.data||[]);if(a.data?.length&&!selectedId)setSelectedId(a.data[0].match_id);}
 async function loadMatch(){if(!selectedId||!user)return;const s=sb();const [e,st,r]=await Promise.all([s.from("match_events").select("*,teams(name),players(full_name,shirt_number)").eq("match_id",selectedId).order("created_at",{ascending:false}),s.from("match_statistics").select("*").eq("match_id",selectedId).maybeSingle(),s.from("match_reports").select("*").eq("match_id",selectedId).eq("reporter_id",user.id).maybeSingle()]);const bad=[e,st,r].find(x=>x.error);if(bad){setError(bad.error.message);return;}setEvents(e.data||[]);setStats(st.data||null);setReport(r.data||null);}
 useEffect(()=>{refresh().finally(()=>setLoading(false));},[]);useEffect(()=>{loadMatch();},[selectedId,user]);useEffect(()=>{if(!selected)return;const f=()=>setTick(elapsed(selected));f();const id=setInterval(f,1000);return()=>clearInterval(id);},[selected]);
 async function assignmentStatus(status){if(!assignment)return;setSaving(true);const r=await sb().from("reporter_assignments").update({status,...(status==="accepted"?{accepted_at:new Date().toISOString()}:{}),...(status==="completed"?{completed_at:new Date().toISOString()}:{} )}).eq("id",assignment.id);setSaving(false);if(r.error)setError(r.error.message);else{setNotice("Assignment updated.");await refresh();}}
 async function matchAction(action){if(!selected)return;const now=new Date().toISOString(),v=action==="start"?{status:"live",kickoff_at:selected.kickoff_at||now}:action==="halftime"?{status:"halftime",halftime_at:now}:action==="resume"?{status:"live",second_half_at:now}:{status:"finished",finished_at:now};setSaving(true);const r=await sb().from("matches").update(v).eq("id",selected.id);setSaving(false);if(r.error)setError(r.error.message);else{setNotice("Match status updated.");await refresh();}}
 async function addEvent(){if(!selected)return;const s=sb();setSaving(true);setError("");if(event.type!=="note"&&event.type!=="var"&&!event.team_id){setError("Select a team.");setSaving(false);return;}const r=await s.from("match_events").insert({match_id:selected.id,team_id:event.team_id||null,player_id:event.player_id||null,secondary_player_id:event.secondary_player_id||null,event_type:event.type,minute:event.minute?Number(event.minute):Math.floor(tick/60),extra_minute:event.extra_minute?Number(event.extra_minute):null,details:event.details||null});if(r.error){setError(r.error.message);setSaving(false);return;}if((event.type==="goal"||event.type==="own_goal")&&event.team_id){const scoring=event.type==="own_goal"?(event.team_id===selected.home_team_id?selected.away_team_id:selected.home_team_id):event.team_id;const v=scoring===selected.home_team_id?{home_score:(selected.home_score||0)+1}:{away_score:(selected.away_score||0)+1};const u=await s.from("matches").update(v).eq("id",selected.id);if(u.error){setError(u.error.message);setSaving(false);return;}}setEvent({type:"goal",team_id:"",player_id:"",secondary_player_id:"",minute:"",extra_minute:"",details:""});setSaving(false);setNotice("Event recorded.");await refresh();await loadMatch();}
 async function saveStats(){if(!selected)return;const v={match_id:selected.id};statRows.forEach(r=>v[r[0]]=Number(stats?.[r[0]]||0),v[r[1]]=Number(stats?.[r[1]]||0));const r=await sb().from("match_statistics").upsert(v,{onConflict:"match_id"});if(r.error)setError(r.error.message);else{setNotice("Statistics saved.");await loadMatch();}}
 async function saveReport(){if(!selected)return;setSaving(true);const v={match_id:selected.id,reporter_id:user.id,summary:report?.summary||"",incidents:report?.incidents||"",status:"submitted",submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()};const r=report?.id?await sb().from("match_reports").update(v).eq("id",report.id):await sb().from("match_reports").insert(v).select("*").single();setSaving(false);if(r.error)setError(r.error.message);else{setNotice("Report submitted.");await assignmentStatus("completed");await loadMatch();}}
 async function signOut(){await sb().auth.signOut();location.href="/login";}
 if(loading)return <main className="auth-page"><div className="panel">Loading Reporter Desk…</div></main>;
 if(!user||!profile||profile.role!=="reporter"||!profile.is_active)return <main className="auth-page"><div className="panel"><h1>Reporter access unavailable</h1><p>{error||"This is a restricted reporter account."}</p><button className="button" onClick={signOut}>Sign out</button></div></main>;
 return <main className="page"><header className="site-header"><div className="container nav"><div className="brand">ZEDEK <span>SPORTS</span> · REPORTER</div><button className="button" onClick={signOut}>Sign out</button></div></header><section className="container page-header"><div className="eyebrow">Restricted · Football Operations</div><h1>Reporter Desk</h1><p>{profile.full_name||user.email} · Assigned matches only.</p></section><section className="container">{error&&<div className="error-box">{error}</div>}{notice&&<div className="success-box">{notice}</div>}
 <div className="stats-grid"><div className="panel"><h2>My assignments</h2>{assignments.map(a=>{const m=matches.find(x=>x.id===a.match_id);return <button key={a.id} className="status-card" onClick={()=>setSelectedId(a.match_id)} style={{display:"block",width:"100%",textAlign:"left",cursor:"pointer"}}><b>{m?.home?.name} vs {m?.away?.name}</b><span>{fmt(m?.scheduled_at)} · {m?.status} · {a.status}</span></button>})}{!assignments.length&&<p className="muted">No matches assigned.</p>}</div><div className="panel"><h2>Assignment</h2>{assignment?<><div className="status-card"><b>{selected?.home?.name} vs {selected?.away?.name}</b><span>{fmt(selected?.scheduled_at)} · {selected?.venue||"Venue TBC"} · {assignment.status}</span></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}>{assignment.status==="assigned"&&<button className="button primary" disabled={saving} onClick={()=>assignmentStatus("accepted")}>Accept</button>}{["accepted","in_progress"].includes(assignment.status)&&<button className="button" disabled={saving} onClick={()=>assignmentStatus("in_progress")}>Start reporting</button>}</div></>:<p className="muted">Select an assignment.</p>}</div></div>
 {selected&&<><div className="panel" style={{marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div className="eyebrow">{selected.status.toUpperCase()}</div><h2>{selected.home?.name} {selected.home_score} : {selected.away_score} {selected.away?.name}</h2><p className="muted">Clock {clock(tick)} · {fmt(selected.scheduled_at)}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{selected.status==="scheduled"&&<button className="button primary" disabled={saving} onClick={()=>matchAction("start")}>Start match</button>}{selected.status==="live"&&<><button className="button" disabled={saving} onClick={()=>matchAction("halftime")}>Half-time</button><button className="button danger" disabled={saving} onClick={()=>matchAction("finish")}>Finish match</button></>}{selected.status==="halftime"&&<button className="button primary" disabled={saving} onClick={()=>matchAction("resume")}>Resume 2nd half</button>}</div></div></div>
 <div className="stats-grid"><div className="panel"><h2>Live events</h2><div className="form-stack"><select value={event.type} onChange={e=>setEvent({...event,type:e.target.value})}><option value="goal">Goal</option><option value="own_goal">Own goal</option><option value="yellow_card">Yellow card</option><option value="red_card">Red card</option><option value="substitution">Substitution</option><option value="penalty_missed">Penalty missed</option><option value="var">VAR</option><option value="note">Match note</option></select><select value={event.team_id} onChange={e=>setEvent({...event,team_id:e.target.value,player_id:"",secondary_player_id:""})}><option value="">Team</option><option value={selected.home_team_id}>{selected.home?.name}</option><option value={selected.away_team_id}>{selected.away?.name}</option></select><select value={event.player_id} onChange={e=>setEvent({...event,player_id:e.target.value})}><option value="">Player</option>{eventPlayers.map(p=><option key={p.id} value={p.id}>#{p.shirt_number||"—"} · {p.full_name}</option>)}</select>{event.type==="goal"&&<select value={event.secondary_player_id} onChange={e=>setEvent({...event,secondary_player_id:e.target.value})}><option value="">Assisted by (optional)</option>{eventPlayers.filter(p=>p.id!==event.player_id).map(p=><option key={p.id} value={p.id}>#{p.shirt_number||"—"} · {p.full_name}</option>)}</select>}{event.type==="substitution"&&<select value={event.secondary_player_id} onChange={e=>setEvent({...event,secondary_player_id:e.target.value})}><option value="">Incoming player</option>{eventPlayers.filter(p=>p.id!==event.player_id).map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select>}<input type="number" placeholder="Minute" value={event.minute} onChange={e=>setEvent({...event,minute:e.target.value})}/><input type="number" placeholder="Added minute" value={event.extra_minute} onChange={e=>setEvent({...event,extra_minute:e.target.value})}/><input placeholder="Details" value={event.details} onChange={e=>setEvent({...event,details:e.target.value})}/><button className="button primary" disabled={saving} onClick={addEvent}>Record event</button></div>{events.map(x=><div className="status-card" key={x.id}><b>{x.minute??"—"}′ · {x.event_type}</b><span>{x.teams?.name||""} · {x.players?.full_name||""} {x.details||""}</span></div>)}</div><div className="panel"><h2>Match statistics</h2>{statRows.map(r=><div className="status-card" key={r[0]}><b>{r[2]}</b><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:8}}><label>{selected.home?.name}<input type="number" step={r[3]} value={stats?.[r[0]]??0} onChange={e=>setStats({...stats,[r[0]]:e.target.value})}/></label><label>{selected.away?.name}<input type="number" step={r[3]} value={stats?.[r[1]]??0} onChange={e=>setStats({...stats,[r[1]]:e.target.value})}/></label></div></div>)}<button className="button primary" disabled={saving} onClick={saveStats}>Save statistics</button></div></div>
 <div className="panel"><h2>Official match report</h2><label>Summary<textarea rows="5" value={report?.summary||""} onChange={e=>setReport({...report,summary:e.target.value})}/></label><label>Incidents<textarea rows="7" value={report?.incidents||""} onChange={e=>setReport({...report,incidents:e.target.value})}/></label><button className="button primary" disabled={saving} onClick={saveReport}>Submit report</button></div></>}</section></main>;
}
