"use client";
import { useEffect,useMemo,useState } from "react";
import { createSupabaseBrowserClient } from "../../../lib/supabase/browser";
type Season={id:string;name:string;competition_id:string}; type Stage={id:string;season_id:string;name:string;stage_type:string;stage_order:number}; type Team={id:string;name:string}; type StageTeam={stage_id:string;team_id:string;group_id:string|null}; type Group={id:string;name:string;stage_id:string}; type Match={id:string;stage_id:string;group_id:string|null;home_team_id:string;away_team_id:string;status:string;home_score:number;away_score:number};
type Row={team_id:string;played:number;won:number;drawn:number;lost:number;gf:number;ga:number;gd:number;points:number};
export default function StandingsPage(){
 const [seasons,setSeasons]=useState<Season[]>([]),[stages,setStages]=useState<Stage[]>([]),[teams,setTeams]=useState<Team[]>([]),[stageTeams,setStageTeams]=useState<StageTeam[]>([]),[groups,setGroups]=useState<Group[]>([]),[matches,setMatches]=useState<Match[]>([]);
 const [seasonId,setSeasonId]=useState(""),[stageId,setStageId]=useState(""),[groupId,setGroupId]=useState(""),[error,setError]=useState("");
 useEffect(()=>{load()},[]);
 async function load(){const s=createSupabaseBrowserClient();const [a,b,c,d,e,f]=await Promise.all([s.from("seasons").select("id,name,competition_id").order("created_at",{ascending:false}),s.from("stages").select("id,season_id,name,stage_type,stage_order").order("stage_order"),s.from("teams").select("id,name"),s.from("stage_teams").select("stage_id,team_id,group_id"),s.from("groups").select("id,name,stage_id").order("group_order"),s.from("matches").select("id,stage_id,group_id,home_team_id,away_team_id,status,home_score,away_score")]);const er=a.error||b.error||c.error||d.error||e.error||f.error;if(er){setError(er.message);return}setSeasons(a.data||[]);setStages(b.data||[]);setTeams(c.data||[]);setStageTeams(d.data||[]);setGroups(e.data||[]);setMatches(f.data||[]);if(!seasonId&&a.data?.length)setSeasonId(a.data[0].id)}
 const seasonStages=useMemo(()=>stages.filter(s=>s.season_id===seasonId),[stages,seasonId]);
 useEffect(()=>{if(seasonStages.length&&!seasonStages.some(s=>s.id===stageId))setStageId(seasonStages[0].id)},[seasonId,seasonStages,stageId]);
 const stageGroups=useMemo(()=>groups.filter(g=>g.stage_id===stageId),[groups,stageId]);
 const stageTeamsFiltered=useMemo(()=>stageTeams.filter(x=>x.stage_id===stageId&&(groupId?x.group_id===groupId:true)),[stageTeams,stageId,groupId]);
 const rows=useMemo(()=>{const map=new Map<string,Row>();stageTeamsFiltered.forEach(x=>map.set(x.team_id,{team_id:x.team_id,played:0,won:0,drawn:0,lost:0,gf:0,ga:0,gd:0,points:0}));matches.filter(m=>(m.status==="finished"||m.status==="verified")&&m.stage_id===stageId&&(groupId?m.group_id===groupId:true)).forEach(m=>{if(!map.has(m.home_team_id)||!map.has(m.away_team_id))return;const h=map.get(m.home_team_id)!,a=map.get(m.away_team_id)!;h.played++;a.played++;h.gf+=m.home_score;h.ga+=m.away_score;a.gf+=m.away_score;a.ga+=m.home_score;if(m.home_score>m.away_score){h.won++;h.points+=3;a.lost++}else if(m.home_score<m.away_score){a.won++;a.points+=3;h.lost++}else{h.drawn++;a.drawn++;h.points++;a.points++}});return [...map.values()].map(r=>({...r,gd:r.gf-r.ga})).sort((x,y)=>y.points-x.points||y.gd-x.gd||y.gf-x.gf||x.team_id.localeCompare(y.team_id))},[stageTeamsFiltered,matches,stageId,groupId]);
 const teamName=(id:string)=>teams.find(t=>t.id===id)?.name||"Unknown";
 return <main className="page"><header className="site-header"><div className="container nav"><a className="brand" href="/control-room">ZEDEK <span>SPORTS</span></a><nav className="nav-links"><a href="/control-room">Dashboard</a><a href="/control-room/reports">Reports</a></nav></div></header>
 <section className="container page-header"><div className="eyebrow">Football Intelligence · Standings Engine</div><h1>Standings</h1><p>Official completed results are converted into live league tables automatically. No duplicate manual standings entry.</p></section>
 <section className="container section"><div className="panel"><div className="form-grid"><label>Season<select value={seasonId} onChange={e=>setSeasonId(e.target.value)}><option value="">Select season</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Stage<select value={stageId} onChange={e=>setStageId(e.target.value)}><option value="">Select stage</option>{seasonStages.map(s=><option key={s.id} value={s.id}>{s.name} · {s.stage_type}</option>)}</select></label>{stageGroups.length>0&&<label>Group<select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">All groups</option>{stageGroups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}</div></div></section>
 <section className="container section"><div className="panel"><div className="section-heading"><div><h2>{stageId?(seasonStages.find(s=>s.id===stageId)?.name||"Stage"):"Standings"}</h2><p>{rows.length} registered teams · {matches.filter(m=>(m.status==="finished"||m.status==="verified")&&m.stage_id===stageId&&(groupId?m.group_id===groupId:true)).length} completed matches counted</p></div></div>{rows.length===0?<div className="status-card">No registered teams or official completed results for this selection yet.</div>:<div className="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>Pts</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.team_id}><td>{i+1}</td><td><b>{teamName(r.team_id)}</b></td><td>{r.played}</td><td>{r.won}</td><td>{r.drawn}</td><td>{r.lost}</td><td>{r.gf}</td><td>{r.ga}</td><td>{r.gd>0?"+":""}{r.gd}</td><td><b>{r.points}</b></td></tr>)}</tbody></table></div>}</div></section>
 {error&&<div className="container error-box">{error}</div>}</main>
}