"use client";
import { useEffect,useState } from "react";
import { createSupabaseBrowserClient } from "../../../lib/supabase/browser";
type Match={id:string;home_team_id:string;away_team_id:string;status:string;home_score:number;away_score:number;scheduled_at:string|null};
type Team={id:string;name:string};
type Report={id:string;match_id:string;summary:string|null;incidents:string|null;status:string;submitted_at:string|null};
type Verification={id:string;match_id:string;corrections:string|null;notes:string|null;official_result:boolean;locked_at:string|null};
export default function ReportsPage(){
 const [matches,setMatches]=useState<Match[]>([]),[teams,setTeams]=useState<Team[]>([]),[reports,setReports]=useState<Report[]>([]),[verifications,setVerifications]=useState<Verification[]>([]);
 const [matchId,setMatchId]=useState(""),[summary,setSummary]=useState(""),[incidents,setIncidents]=useState(""),[corrections,setCorrections]=useState(""),[notes,setNotes]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const match=matches.find(m=>m.id===matchId),report=reports.find(r=>r.match_id===matchId),verification=verifications.find(v=>v.match_id===matchId);
 const teamName=(id:string)=>teams.find(t=>t.id===id)?.name||"Unknown";
 useEffect(()=>{load()},[]);
 async function load(){const s=createSupabaseBrowserClient();const [m,t,r,v]=await Promise.all([s.from("matches").select("id,home_team_id,away_team_id,status,home_score,away_score,scheduled_at").order("scheduled_at",{ascending:false}),s.from("teams").select("id,name"),s.from("match_reports").select("*"),s.from("match_verifications").select("*")]);const e=m.error||t.error||r.error||v.error;if(e)setError(e.message);else{setMatches(m.data||[]);setTeams(t.data||[]);setReports(r.data||[]);setVerifications(v.data||[]);if(!matchId&&m.data?.length)setMatchId(m.data[0].id)}}
 useEffect(()=>{if(report){setSummary(report.summary||"");setIncidents(report.incidents||"")}else{setSummary("");setIncidents("")}},[report?.id]);
 async function saveReport(status:string){if(!match)return;setBusy(true);setError("");const s=createSupabaseBrowserClient();const payload={match_id:match.id,summary:summary.trim()||null,incidents:incidents.trim()||null,status,submitted_at:status==="submitted"?new Date().toISOString():report?.submitted_at||null,updated_at:new Date().toISOString()};const q=report?s.from("match_reports").update(payload).eq("id",report.id):s.from("match_reports").insert(payload);const {error}=await q;if(error)setError(error.message);else{setNotice(status==="submitted"?"Report submitted for verification.":"Report saved as draft.");await load()}setBusy(false)}
 async function verify(lock:boolean){if(!match)return;setBusy(true);setError("");const s=createSupabaseBrowserClient();const payload={match_id:match.id,corrections:corrections.trim()||null,notes:notes.trim()||null,official_result:true,verified_at:new Date().toISOString(),locked_at:lock?new Date().toISOString():null};const q=verification?s.from("match_verifications").update(payload).eq("id",verification.id):s.from("match_verifications").insert(payload);const {error}=await q;if(error)setError(error.message);else{const result=await s.from("matches").update({status:lock?"verified":"finished"}).eq("id",match.id);if(result.error)setError(result.error.message);else{setNotice(lock?"Official result verified and locked.":"Result verified.");await load()}}setBusy(false)}
 return <main className="page"><header className="site-header"><div className="container nav"><a className="brand" href="/control-room">ZEDEK <span>SPORTS</span></a><nav className="nav-links"><a href="/control-room/match-control">Match Control</a><a href="/control-room">Dashboard</a></nav></div></header>
 <section className="container page-header"><div className="eyebrow">Football Operations · Reports & Verification</div><h1>Match Reporting & Verification</h1><p>Submit match reports, review corrections, verify official results and lock completed matches.</p></section>
 <section className="container section"><div className="panel"><label>Match<select value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">Select match</option>{matches.map(m=><option key={m.id} value={m.id}>{teamName(m.home_team_id)} {m.home_score}-{m.away_score} {teamName(m.away_team_id)} · {m.status}</option>)}</select></label></div></section>
 {match&&<><section className="container section"><div className="panel"><h2>{teamName(match.home_team_id)} {match.home_score} - {match.away_score} {teamName(match.away_team_id)}</h2><div className="form-stack"><label>Match report<textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Official match summary"/></label><label>Incidents / corrections<textarea value={incidents} onChange={e=>setIncidents(e.target.value)} placeholder="Important incidents, corrections or report notes"/></label><div className="button-row"><button className="button" disabled={busy} onClick={()=>saveReport("draft")}>Save draft</button><button className="button primary" disabled={busy} onClick={()=>saveReport("submitted")}>Submit report</button></div></div></div></section>
 <section className="container section"><div className="panel"><h2>Verification</h2><div className="form-stack"><label>Corrections<textarea value={corrections} onChange={e=>setCorrections(e.target.value)} placeholder="Verified corrections"/></label><label>Verification notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="button-row"><button className="button primary" disabled={busy||match.status==="verified"} onClick={()=>verify(false)}>Verify result</button><button className="button danger" disabled={busy||match.status==="verified"} onClick={()=>verify(true)}>Verify & lock official result</button></div>{verification&&<div className="status-card"><b>{verification.official_result?"OFFICIAL RESULT":"PENDING"}</b>{verification.locked_at&&<span> Locked {new Date(verification.locked_at).toLocaleString()}</span>}</div>}</div></div></section></>}
 {notice&&<div className="container success-box">{notice}</div>}{error&&<div className="container error-box">{error}</div>}</main>
}