"use client";

import { FormEvent, useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "../../../lib/supabase/browser";

type Team={id:string;name:string;area:string|null;is_active:boolean};
type Coach={id:string;full_name:string;date_of_birth:string|null;nationality:string|null;role:string;is_active:boolean};
type Assignment={id:string;team_id:string;coach_id:string;start_date:string|null;end_date:string|null;is_current:boolean};

export default function CoachesPage(){
 const [teams,setTeams]=useState<Team[]>([]),[coaches,setCoaches]=useState<Coach[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]);
 const [teamId,setTeamId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [form,setForm]=useState({full_name:"",date_of_birth:"",nationality:"",role:"Head Coach"});
 async function load(){setLoading(true);setError("");const s=createSupabaseBrowserClient();const [t,c,a]=await Promise.all([s.from("teams").select("id,name,area,is_active").order("name"),s.from("coaches").select("id,full_name,date_of_birth,nationality,role,is_active").order("full_name"),s.from("team_coaches").select("id,team_id,coach_id,start_date,end_date,is_current")]);const bad=t.error||c.error||a.error;if(bad)setError(bad.message);else{setTeams(t.data||[]);setCoaches(c.data||[]);setAssignments(a.data||[]);if(!teamId&&t.data?.length)setTeamId(t.data[0].id)}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function add(e:FormEvent){e.preventDefault();setSaving(true);setError("");setNotice("");const s=createSupabaseBrowserClient();const {error}=await s.from("coaches").insert({full_name:form.full_name.trim(),date_of_birth:form.date_of_birth||null,nationality:form.nationality.trim()||null,role:form.role.trim()||"Head Coach"});if(error)setError(error.message);else{setForm({full_name:"",date_of_birth:"",nationality:"",role:"Head Coach"});setNotice("Coach added.");await load()}setSaving(false)}
 async function assign(c:Coach){if(!teamId)return;const s=createSupabaseBrowserClient();setError("");await s.from("team_coaches").update({is_current:false,end_date:new Date().toISOString().slice(0,10)}).eq("team_id",teamId).eq("is_current",true);const {error}=await s.from("team_coaches").insert({team_id:teamId,coach_id:c.id,is_current:true,start_date:new Date().toISOString().slice(0,10)});if(error)setError(error.message);else{setNotice(c.full_name+" assigned to team.");await load()}}
 async function endAssignment(a:Assignment){const s=createSupabaseBrowserClient();const {error}=await s.from("team_coaches").update({is_current:false,end_date:new Date().toISOString().slice(0,10)}).eq("id",a.id);if(error)setError(error.message);else{setNotice("Coach assignment ended.");await load()}}
 async function toggle(c:Coach){const s=createSupabaseBrowserClient();const {error}=await s.from("coaches").update({is_active:!c.is_active}).eq("id",c.id);if(error)setError(error.message);else await load()}
 async function remove(c:Coach){if(!window.confirm("Archive "+c.full_name+"? Historical assignments will be preserved."))return;const s=createSupabaseBrowserClient();const {error}=await s.from("coaches").update({is_active:false}).eq("id",c.id);if(error)setError(error.message);else{setNotice("Coach archived.");await load()}}
 const current=assignments.filter(a=>a.team_id===teamId&&a.is_current), history=assignments.filter(a=>a.team_id===teamId&&!a.is_current);
 return <main className="page"><header className="site-header"><div className="container nav"><a className="brand" href="/control-room">ZEDEK <span>SPORTS</span></a><nav className="nav-links"><a href="/control-room">Control Room</a><a href="/control-room/teams">Teams</a><a href="/control-room/players">Players</a></nav></div></header>
 <section className="container page-header"><div className="eyebrow">Football Operations · Phase 2</div><h1>Coach Management</h1><p>Create coaches, assign them to teams, transfer assignments and preserve coaching history.</p></section>
 <section className="container section"><div className="panel"><h2>Add coach</h2><form className="form-stack" onSubmit={add}><label>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Role<input value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/></label><label>Nationality<input value={form.nationality} onChange={e=>setForm({...form,nationality:e.target.value})}/></label><label>Date of birth<input type="date" value={form.date_of_birth} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></label><button className="button primary" disabled={saving}>{saving?"Adding...":"Add coach"}</button></form></div></section>
 <section className="container section"><div className="panel"><h2>Team assignment</h2><label>Team<select value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">Select team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{teamId&&<><h3>Current coach</h3>{current.length?current.map(a=>{const c=coaches.find(x=>x.id===a.coach_id);return <article className="module" key={a.id}><strong>{c?.full_name||"Unknown coach"}</strong><small>{c?.role||"Role"} · Since {a.start_date||"—"}</small><button className="button danger" onClick={()=>endAssignment(a)}>End assignment</button></article>}):<p>No current coach assigned.</p>}<h3>Available coaches</h3><div className="module-grid">{coaches.filter(c=>c.is_active).map(c=><article className="module" key={c.id}><strong>{c.full_name}</strong><small>{c.role}{c.nationality?" · "+c.nationality:""}</small><button className="button" onClick={()=>assign(c)}>Assign to team</button></article>)}</div></>}</div></section>
 <section className="container section"><div className="section-heading"><h2>Coach registry</h2><span>{coaches.length} coaches</span></div>{loading?<p>Loading...</p>:<div className="module-grid">{coaches.map(c=><article className="module" key={c.id}><strong>{c.full_name}</strong><small>{c.role}{c.nationality?" · "+c.nationality:""} · {c.is_active?"Active":"Inactive"}</small><div className="button-row"><button className="button" onClick={()=>toggle(c)}>{c.is_active?"Deactivate":"Activate"}</button><button className="button danger" onClick={()=>remove(c)}>Delete</button></div></article>)}</div>}</section>
 <section className="container section"><div className="panel"><h2>Team coaching history</h2>{history.length===0?<p>No previous coaching assignments for this team.</p>:history.map(a=><article className="module" key={a.id}><strong>{coaches.find(c=>c.id===a.coach_id)?.full_name||"Unknown coach"}</strong><small>{a.start_date||"—"} to {a.end_date||"—"}</small></article>)}</div></section>
 {notice&&<div className="container success-box">{notice}</div>}{error&&<div className="container error-box">{error}</div>}</main>
}